In [2]:
import pandas as pd 

# Print the pandas version 
print(f"Pandas version: {pd.__version__}")

Pandas version: 2.0.3


### Empty Series Object: 

In [3]:
# Creating empty Series object 
s = pd.Series()
print(s, type(s)) 

Series([], dtype: object) <class 'pandas.core.series.Series'>


### Create Series Object using List:

In [4]:
# Creating series object using list 
m = [111, 222, 333, 444, 555]
s = pd.Series(m) 
print(s) 

0    111
1    222
2    333
3    444
4    555
dtype: int64


### Create Series object using List, assigning a name 

In [5]:
# Creating series object using list and assigning a name 
s = pd.Series(m, name = "marks") 
print(s) 

0    111
1    222
2    333
3    444
4    555
Name: marks, dtype: int64


In [6]:
n = ["Pushpa", "RRR", "Gangubhai", "KFG Chapter 2"]
s = pd.Series(n, name = "movies") 
print(s) 

0           Pushpa
1              RRR
2        Gangubhai
3    KFG Chapter 2
Name: movies, dtype: object


### Create a Series object by using range and list 

In [8]:
# Using Range and List
r = range(100) 
a = list(r) 
s = pd.Series(a) 
print(s) 

0      0
1      1
2      2
3      3
4      4
      ..
95    95
96    96
97    97
98    98
99    99
Length: 100, dtype: int64


### Creating a Series from Array

In [10]:
# Creating ndarray
import numpy as np 

values = [10, 20, 30, 40]
data = np.array(values) 

print(data, type(data))

s = pd.Series(data) 
print(s) 

[10 20 30 40] <class 'numpy.ndarray'>
0    10
1    20
2    30
3    40
dtype: int32


In [11]:
# Creating Series using ndarray 
actors = ["Allu Arjun", "Ram Charan", "Jr. NTR", "Prabhas"]
data = np.array(actors) 
s = pd.Series(data) 
print(s) 

0    Allu Arjun
1    Ram Charan
2       Jr. NTR
3       Prabhas
dtype: object


In [12]:
# Creating Series using ndarray 
actress = ["Kriti", "Alia", "Deepika", "Kareena"]
data = np.array(actress) 
s = pd.Series(data) 
print(s) 

0      Kriti
1       Alia
2    Deepika
3    Kareena
dtype: object


### Index in Series

In [14]:
# Creating Series object and giving name
v = [145, 142, 38, 13]
s = pd.Series(v, name = "counts") 
print(s) 

0    145
1    142
2     38
3     13
Name: counts, dtype: int64


In [16]:
# Creating Series object and giving name and index 
i = [10, 20, 30, 40]
s = pd.Series(v, name = "counts", index = i) 
print(s) 

10    145
20    142
30     38
40     13
Name: counts, dtype: int64


In [17]:
# Creating Series object and giving name and index 
prices = [1000, 2000, 3000, 4000]
products = ["Nokia", "Samsung", "Oppo", "iPhone6"]
s = pd.Series(prices, name = "mobiles", index = products) 
print(s) 

Nokia      1000
Samsung    2000
Oppo       3000
iPhone6    4000
Name: mobiles, dtype: int64


### Creating Series and Accessing Values 

In [19]:
# Creating Series and Accessing values 
v = [56, 45, 35, 41, 44, 60]
s = pd.Series(v, name = "marks") 
print(s) 
print()
print(s[0], s[1], s[2], s[3], s[4], s[5]) 

0    56
1    45
2    35
3    41
4    44
5    60
Name: marks, dtype: int64

56 45 35 41 44 60


In [21]:
# Creating Series and Accessing Values 
prices = [1000, 2000, 3000, 4000]
products = ["Nokia", "Samsung", "Oppo", "iPhone"]
s = pd.Series(prices, name = "mobiles", index = products)
print(s) 
print()
print(s["Nokia"]) 
print(s["Samsung"]) 

Nokia      1000
Samsung    2000
Oppo       3000
iPhone     4000
Name: mobiles, dtype: int64

1000
2000


### NaN Values: 

In [23]:
# Creating Series with NaN values 
marks = [36, 70, np.nan, 60]
s = pd.Series(marks) 
print(s) 

0    36.0
1    70.0
2     NaN
3    60.0
dtype: float64


In [24]:
# Creating Series with NaN values 
names = ["Arjun", "Krishna", "Draupadi", "Karna"]
s = pd.Series(names) 
print(s) 

0       Arjun
1     Krishna
2    Draupadi
3       Karna
dtype: object


### Series Attributes

1. `values`
2. `index`
3. `dtypes`
4. `size`

`values`: a pre-defined attribute in Series class

In [26]:
# Accessing values attribute 
marks = [111, 222, 333, 444, 555, 666]
s = pd.Series(marks) 
print(s) 
print(s.values) 

0    111
1    222
2    333
3    444
4    555
5    666
dtype: int64
[111 222 333 444 555 666]


In [27]:
# Accessing values attribute 
names = ["RRR", "Bahubali", "Pushpa", "KGF"]
s = pd.Series(names) 
print(s)
print(s.values) 

0         RRR
1    Bahubali
2      Pushpa
3         KGF
dtype: object
['RRR' 'Bahubali' 'Pushpa' 'KGF']


`index` attribute: a pre-defined attribute in Series class

In [28]:
print(s.index)

RangeIndex(start=0, stop=4, step=1)


In [30]:
s.index

Index([11, 22, 33, 44, 55], dtype='int64')

In [29]:
marks = [111, 222, 333, 444, 555]
i = [11, 22, 33, 44, 55]
s = pd.Series(marks, index = i) 
print(s) 
print(s.index) 

11    111
22    222
33    333
44    444
55    555
dtype: int64
Index([11, 22, 33, 44, 55], dtype='int64')


`dtypes:` a pre-defined attribute in Series class

In [31]:
s.dtypes 

dtype('int64')

In [32]:
# Accessing dtypes attribute 
salaries = [1000.0, 2000.0, 3000.0, 4000.0, 5000.0]
s = pd.Series(salaries) 
print(s, s.dtypes) 

0    1000.0
1    2000.0
2    3000.0
3    4000.0
4    5000.0
dtype: float64 float64


In [33]:
# Accessing dtypes attributes 
names = ["Ram", "Allu", "NTR", "Teja"]
s = pd.Series(names) 
print(s, s.dtypes) 

0     Ram
1    Allu
2     NTR
3    Teja
dtype: object object


`size` attribute: 

In [35]:
# Accessing size attribute
marks = [56, 45, 35, 41, 44, 60]
s = pd.Series(marks) 
print(s) 
print(s.size) 

0    56
1    45
2    35
3    41
4    44
5    60
dtype: int64
6


### Series Methods:

1. `head()`
2. `tail()`
3. `sum()`
4. `count()`
5. `mean()`
6. `describe()`
7. `unique()`
8. `nunique()`

#### `head()`

In [37]:
# Accessing first five values from Series
marks = [56, 45, 35, 41, 60, 57, 56, 56]
s = pd.Series(marks) 

print(s) 
print()
print(s.head())

0    56
1    45
2    35
3    41
4    60
5    57
6    56
7    56
dtype: int64

0    56
1    45
2    35
3    41
4    60
dtype: int64


#### `tail()`

In [38]:
print(s) 
print()
print(s.tail())

0    56
1    45
2    35
3    41
4    60
5    57
6    56
7    56
dtype: int64

3    41
4    60
5    57
6    56
7    56
dtype: int64


#### `sum():`

In [39]:
# Sum of series of values 
sales = [56, 45, 35, 41, 44, 60]
s = pd.Series(sales) 
print(s)
print(s.sum())

0    56
1    45
2    35
3    41
4    44
5    60
dtype: int64
281


In [40]:
# Get the sum of series of values 
marks = [56, 45, 35, 41, np.nan, 60, np.nan]
s = pd.Series(marks) 
print(s) 
print(s.sum())

0    56.0
1    45.0
2    35.0
3    41.0
4     NaN
5    60.0
6     NaN
dtype: float64
237.0


#### `count()`

In [41]:
marks = [56, 45, 35, 41, np.nan, 60, np.nan]
s = pd.Series(marks) 
print(s) 
print(s.count())

0    56.0
1    45.0
2    35.0
3    41.0
4     NaN
5    60.0
6     NaN
dtype: float64
5


#### `mean()`

In [42]:
sales = [1000, 2000, 3000, 4000, 5000]
s = pd.Series(sales) 
print(s) 
print(s.mean())

0    1000
1    2000
2    3000
3    4000
4    5000
dtype: int64
3000.0


#### `describe()`

In [43]:
print(s.describe())

count       5.00000
mean     3000.00000
std      1581.13883
min      1000.00000
25%      2000.00000
50%      3000.00000
75%      4000.00000
max      5000.00000
dtype: float64


In [44]:
s.describe()

count       5.00000
mean     3000.00000
std      1581.13883
min      1000.00000
25%      2000.00000
50%      3000.00000
75%      4000.00000
max      5000.00000
dtype: float64

#### `unique()`

In [45]:
marks = [56, 45, 35, 41, 60, 57, 56, 56]
s = pd.Series(marks) 
print(s) 
print(s.unique())

0    56
1    45
2    35
3    41
4    60
5    57
6    56
7    56
dtype: int64
[56 45 35 41 60 57]


In [46]:
print(s.nunique())

6
