# **Numpy**

## **Array Attributes:**

1. `a.ndim:` Returns the dimension of the array 
2. `a.shape:` Returns the shape of the array 
3. `size:` To get total number of elements 
4. `dtype:` To get data type of array elements 
5. `itemsize:` four bytes  

In [1]:
import numpy as np

In [2]:
a = np.array([10, 20, 30, 40, 50]) 
a 

array([10, 20, 30, 40, 50])

In [3]:
a.ndim, a.shape, a.size, a.dtype, a.itemsize

(1, (5,), 5, dtype('int32'), 4)

In [5]:
print(f"The dimension of an array: {a.ndim}") 
print(f"The shape of an array: {a.shape}") 
print(f"The size of an array: {a.size}") 
print(f"The data type of an array: {a.dtype}") 
print(f"The item size of an array: {a.itemsize}") # 32 bits = 4 bytes 

The dimension of an array: 1
The shape of an array: (5,)
The size of an array: 5
The data type of an array: int32
The item size of an array: 4


In [7]:
a = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]], dtype = "float")
a 

array([[10., 20., 30.],
       [40., 50., 60.],
       [70., 80., 90.]])

In [8]:
print(f"The dimension of an array: {a.ndim}") 
print(f"The shape of an array: {a.shape}") 
print(f"The size of an array: {a.size}") 
print(f"The data type of an array: {a.dtype}") 
print(f"The item size of an array: {a.itemsize}") # 32 bits = 4 bytes 

The dimension of an array: 2
The shape of an array: (3, 3)
The size of an array: 9
The data type of an array: float64
The item size of an array: 8


## **Numpy Datatypes:**

**Extra datatypes available in Numpy:** 
* `i`: integer (int8, int16, int32, int64)
* `b`: boolean 
* `u`: unsigned integer 
* `f`: float (float16, float32, float64)
* `c`: complex (complex64, complex28)
* `U`: unicode string
* `M`: datetime 

In [16]:
a = np.array([10, 0, 20, 30, 0, 40, 50, 60]) 
b = a.astype("float64") 

In [17]:
a.dtype, b.dtype 

(dtype('int32'), dtype('float64'))

In [18]:
f = np.float64(a) 
a.dtype,  f.dtype

(dtype('int32'), dtype('float64'))

In [19]:
x = np.bool_(a)
x

array([ True, False,  True,  True, False,  True,  True,  True])